apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name | quote }}
  labels:
     {{- include "common.labels" . | nindent 4 }}
  {{- if or .Values.annotations .Values.letsencrypt.enabled }}
  annotations:
  {{- end }}
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.letsencrypt.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.letsencrypt.issuer | quote }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          {{- range .Values.paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .port }}
          {{- end }}
  tls:
    - hosts:
        - {{ .Values.host | quote }}
      {{- if .Values.letsencrypt.enabled }}
      secretName: "{{ .Values.name }}-ingress-tls"
      {{- end }}