permissions:
  contents: read
  packages: write
#  id-token: write # required to use OIDC authentication

concurrency: ci-${{ github.ref }}

name: Build and Publish Charts
on:
  push:
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        chart: 
          - ingress
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Helm Lint
        run: helm lint ${{ matrix.chart }}/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2
      - name: Run chart-testing (lint)
        run: ct lint --charts ${{ matrix.chart }}/

  helm_publish:
    needs: testing
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 1
      matrix:
        chart: 
          - ingress
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Helm package and push
        run: |
          helm package ${{ matrix.chart }}
          tar="$(find *.tgz)"
          helm push $tar oci://ghcr.io/sierra1011/helm
